/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ReservationAndGuestStay_m2;
import RoomManagement_m1.Room;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Garam
 */
public class ReservationGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReservationGUI.class.getName());
    private ReservationManager manager;
    private ReservationFiles files;
    private RoomService roomService;
    
    /**
     * Creates new form ReservationGUI
     */
    public ReservationGUI() {
        initComponents();
        setLocationRelativeTo(null);

// Table header design
javax.swing.table.DefaultTableCellRenderer header =
        new javax.swing.table.DefaultTableCellRenderer();

header.setBackground(
        new java.awt.Color(31, 78, 78)
);

header.setForeground(
        java.awt.Color.WHITE
);

header.setFont(
        new java.awt.Font(
                "Segoe UI",
                java.awt.Font.BOLD,
                13
        )
);

header.setHorizontalAlignment(
        javax.swing.SwingConstants.CENTER
);

tblReservations.getTableHeader()
        .setDefaultRenderer(header);

// Table design
tblReservations.setRowHeight(28);

tblReservations.setSelectionBackground(
        new java.awt.Color(197, 164, 109)
);

tblReservations.setSelectionForeground(
        java.awt.Color.BLACK
);


        manager = new ReservationManager();
        files = new ReservationFiles(manager);
        roomService = new RoomService();

        files.loadReservations();
        loadAvailableRooms();
        refreshTable();
    }
private void loadAvailableRooms() {

    cmbRoomNumber.removeAllItems();

    for (Room room : roomService.getAvailableRooms()) {
        cmbRoomNumber.addItem(
                String.valueOf(room.getRoomNumber())
        );
    }
}

private void refreshTable() {

    DefaultTableModel model =
            (DefaultTableModel) tblReservations.getModel();

    model.setRowCount(0);

    for (Reservation reservation : manager.getReservations()) {

        model.addRow(new Object[]{
            reservation.getReservationId(),
            reservation.getGuestName(),
            reservation.getGuestPhone(),
            reservation.getGuestEmail(),
            reservation.getPassportNumber(),
            reservation.getRoomNumber(),
            reservation.getCheckInDate(),
            reservation.getCheckOutDate(),
            reservation.calculateNumberOfNights(),
            reservation.getReservationStatus()
        });
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtReservationId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCheckInDate = new javax.swing.JTextField();
        txtPassportNumber = new javax.swing.JTextField();
        txtGuestPhone = new javax.swing.JTextField();
        txtGuestEmail = new javax.swing.JTextField();
        txtCheckOutDate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtGuestName = new javax.swing.JTextField();
        cmbRoomNumber = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnCheckIn = new javax.swing.JButton();
        btnCheckOut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReservations = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Reservation ID:");

        txtReservationId.addActionListener(this::txtReservationIdActionPerformed);

        jLabel2.setText("Passport/Civil ID:");

        jLabel3.setText("Email:");

        jLabel4.setText("Guest Name:");

        jLabel5.setText("Room Number:");

        jLabel6.setText("Check-in (dd/MM/yyyy):");

        jLabel7.setText("Check-out (dd/MM/yyyy):");

        txtCheckInDate.addActionListener(this::txtCheckInDateActionPerformed);

        txtGuestPhone.addActionListener(this::txtGuestPhoneActionPerformed);

        txtCheckOutDate.addActionListener(this::txtCheckOutDateActionPerformed);

        jLabel8.setText("Phone");

        txtGuestName.addActionListener(this::txtGuestNameActionPerformed);

        cmbRoomNumber.addActionListener(this::cmbRoomNumberActionPerformed);

        btnAdd.setText("Add Reservation");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        btnCheckIn.setText("Check in");
        btnCheckIn.addActionListener(this::btnCheckInActionPerformed);

        btnCheckOut.setText("Check Out");
        btnCheckOut.addActionListener(this::btnCheckOutActionPerformed);

        tblReservations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Reservation ID", "Guest Name", "Phone", "Email", "Passport ID", "Room", "Check in", "Check out", "Nights", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblReservations.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblReservations);
        tblReservations.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel9.setText("Reservation Details");

        btnExit.setText("Exit");
        btnExit.addActionListener(this::btnExitActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtGuestPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                            .addComponent(txtGuestEmail)
                                            .addComponent(txtGuestName)
                                            .addComponent(txtReservationId)
                                            .addComponent(txtCheckInDate)
                                            .addComponent(txtCheckOutDate)
                                            .addComponent(txtPassportNumber)
                                            .addComponent(cmbRoomNumber, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnCheckOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(160, 160, 160))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(btnExit)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(btnAdd)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnCancel)))
                                                .addGap(11, 11, 11))))))))
                    .addComponent(jScrollPane1))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(15, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)
                                        .addGap(6, 6, 6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtReservationId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtGuestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtGuestEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCancel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addComponent(txtGuestPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassportNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCheckInDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheckIn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCheckOutDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheckOut)
                    .addComponent(btnExit))
                .addGap(68, 68, 68)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtReservationIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReservationIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReservationIdActionPerformed

    private void txtGuestNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuestNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGuestNameActionPerformed

    private void txtGuestPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuestPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGuestPhoneActionPerformed

    private void txtCheckInDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckInDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckInDateActionPerformed

    private void txtCheckOutDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckOutDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckOutDateActionPerformed

    private void cmbRoomNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoomNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRoomNumberActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {

    if (cmbRoomNumber.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(
                this,
                "No available room was selected."
        );
        return;
    }

    int reservationId =
            Integer.parseInt(txtReservationId.getText());

    int roomNumber =
            Integer.parseInt(
                    cmbRoomNumber.getSelectedItem().toString()
            );

    if (manager.searchById(reservationId) != null) {
        JOptionPane.showMessageDialog(
                this,
                "This reservation ID already exists."
        );
        return;
    }

    Reservation reservation = new Reservation(
            reservationId,
            txtGuestName.getText(),
            txtGuestPhone.getText(),
            txtGuestEmail.getText(),
            txtPassportNumber.getText(),
            roomNumber,
            txtCheckInDate.getText(),
            txtCheckOutDate.getText(),
            ReservationStatus.RESERVED
    );

    if (reservation.calculateNumberOfNights() <= 0) {
        JOptionPane.showMessageDialog(
                this,
                "Check-out must be after check-in."
        );
        return;
    }

    if (!roomService.reserveRoom(roomNumber)) {
        JOptionPane.showMessageDialog(
                this,
                "This room is not available."
        );
        return;
    }

    manager.addReservation(reservation);
    files.saveReservations();

    refreshTable();
    loadAvailableRooms();

    JOptionPane.showMessageDialog(
            this,
            "Reservation added successfully."
    );

} catch (NumberFormatException e) {

    JOptionPane.showMessageDialog(
            this,
            "Reservation ID must be a number."
    );

} catch (Exception e) {

    JOptionPane.showMessageDialog(
            this,
            "Enter the dates as dd/MM/yyyy."
    );
}
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
       try {

    int reservationId =
            Integer.parseInt(txtReservationId.getText());

    Reservation reservation =
            manager.searchById(reservationId);

    if (reservation == null) {

        JOptionPane.showMessageDialog(
                this,
                "Reservation not found."
        );

        return;
    }

    int answer = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to cancel this reservation?",
            "Confirm Cancellation",
            JOptionPane.YES_NO_OPTION
    );

    if (answer != JOptionPane.YES_OPTION) {
        return;
    }

    if (!manager.cancelReservation(reservationId)) {

        JOptionPane.showMessageDialog(
                this,
                "This reservation cannot be cancelled."
        );

        return;
    }

    roomService.releaseRoom(
            reservation.getRoomNumber()
    );

    files.saveReservations();
    refreshTable();
    loadAvailableRooms();

    JOptionPane.showMessageDialog(
            this,
            "Reservation cancelled successfully."
    );

} catch (NumberFormatException e) {

    JOptionPane.showMessageDialog(
            this,
            "Enter a valid reservation ID."
    );
}
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {

    int reservationId =
            Integer.parseInt(txtReservationId.getText());

    Reservation currentReservation =
            manager.searchById(reservationId);

    if (currentReservation == null) {

        JOptionPane.showMessageDialog(
                this,
                "Reservation not found."
        );

        return;
    }

    if (cmbRoomNumber.getSelectedItem() == null) {

        JOptionPane.showMessageDialog(
                this,
                "Select a room."
        );

        return;
    }

    int newRoomNumber =
            Integer.parseInt(
                    cmbRoomNumber.getSelectedItem().toString()
            );

    Reservation editedReservation = new Reservation(
            reservationId,
            txtGuestName.getText(),
            txtGuestPhone.getText(),
            txtGuestEmail.getText(),
            txtPassportNumber.getText(),
            newRoomNumber,
            txtCheckInDate.getText(),
            txtCheckOutDate.getText(),
            currentReservation.getReservationStatus()
    );

    if (editedReservation.calculateNumberOfNights() <= 0) {

        JOptionPane.showMessageDialog(
                this,
                "Check-out must be after check-in."
        );

        return;
    }

    int oldRoomNumber =
            currentReservation.getRoomNumber();

    if (newRoomNumber != oldRoomNumber) {

        if (currentReservation.getReservationStatus()
                != ReservationStatus.RESERVED) {

            JOptionPane.showMessageDialog(
                    this,
                    "The room cannot be changed after check-in."
            );

            return;
        }

        if (!roomService.reserveRoom(newRoomNumber)) {

            JOptionPane.showMessageDialog(
                    this,
                    "The new room is not available."
            );

            return;
        }

        roomService.releaseRoom(oldRoomNumber);
    }

    manager.editReservation(
            reservationId,
            txtGuestName.getText(),
            txtGuestPhone.getText(),
            txtGuestEmail.getText(),
            txtPassportNumber.getText(),
            newRoomNumber,
            txtCheckInDate.getText(),
            txtCheckOutDate.getText()
    );

    files.saveReservations();
    refreshTable();
    loadAvailableRooms();

    JOptionPane.showMessageDialog(
            this,
            "Reservation updated successfully."
    );

} catch (NumberFormatException e) {

    JOptionPane.showMessageDialog(
            this,
            "Enter a valid reservation ID."
    );

} catch (Exception e) {

    JOptionPane.showMessageDialog(
            this,
            "Enter the dates as dd/MM/yyyy."
    );
}
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
       try {

    int reservationId =
            Integer.parseInt(txtReservationId.getText());

    Reservation reservation =
            manager.searchById(reservationId);

    if (reservation == null) {

        JOptionPane.showMessageDialog(
                this,
                "Reservation not found."
        );

        return;
    }

    txtGuestName.setText(
            reservation.getGuestName()
    );

    txtGuestPhone.setText(
            reservation.getGuestPhone()
    );

    txtGuestEmail.setText(
            reservation.getGuestEmail()
    );

    txtPassportNumber.setText(
            reservation.getPassportNumber()
    );

    txtCheckInDate.setText(
            reservation.getCheckInDate()
    );

    txtCheckOutDate.setText(
            reservation.getCheckOutDate()
    );

    String roomNumber =
            String.valueOf(reservation.getRoomNumber());

    boolean roomExists = false;

    for (int i = 0; i < cmbRoomNumber.getItemCount(); i++) {

        if (cmbRoomNumber.getItemAt(i).equals(roomNumber)) {
            roomExists = true;
            break;
        }
    }

    if (!roomExists) {
        cmbRoomNumber.addItem(roomNumber);
    }

    cmbRoomNumber.setSelectedItem(roomNumber);

    JOptionPane.showMessageDialog(
            this,
            "Reservation found."
    );

} catch (NumberFormatException e) {

    JOptionPane.showMessageDialog(
            this,
            "Enter a valid reservation ID."
    );
}
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed
        try {

    int reservationId =
            Integer.parseInt(txtReservationId.getText());

    Reservation reservation =
            manager.searchById(reservationId);

    if (reservation == null) {

        JOptionPane.showMessageDialog(
                this,
                "Reservation not found."
        );

        return;
    }

    if (reservation.getReservationStatus()
            != ReservationStatus.RESERVED) {

        JOptionPane.showMessageDialog(
                this,
                "Only a reserved guest can check in."
        );

        return;
    }

    if (!roomService.occupyRoom(
            reservation.getRoomNumber())) {

        JOptionPane.showMessageDialog(
                this,
                "The room could not be marked as occupied."
        );

        return;
    }

    manager.checkInCheckOut(
            reservationId,
            ReservationStatus.CHECKED_IN
    );

    files.saveReservations();
    refreshTable();

    JOptionPane.showMessageDialog(
            this,
            "Guest checked in successfully."
    );

} catch (NumberFormatException e) {

    JOptionPane.showMessageDialog(
            this,
            "Enter a valid reservation ID."
    );
}
    }//GEN-LAST:event_btnCheckInActionPerformed

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        try {

    int reservationId =
            Integer.parseInt(txtReservationId.getText());

    Reservation reservation =
            manager.searchById(reservationId);

    if (reservation == null) {

        JOptionPane.showMessageDialog(
                this,
                "Reservation not found."
        );

        return;
    }

    if (reservation.getReservationStatus()
            != ReservationStatus.CHECKED_IN) {

        JOptionPane.showMessageDialog(
                this,
                "Only a checked-in guest can check out."
        );

        return;
    }

    if (!roomService.releaseRoom(
            reservation.getRoomNumber())) {

        JOptionPane.showMessageDialog(
                this,
                "The room could not be released."
        );

        return;
    }

    manager.checkInCheckOut(
            reservationId,
            ReservationStatus.CHECKED_OUT
    );

    files.saveReservations();
    refreshTable();
    loadAvailableRooms();

    JOptionPane.showMessageDialog(
            this,
            "Guest checked out successfully."
    );

} catch (NumberFormatException e) {

    JOptionPane.showMessageDialog(
            this,
            "Enter a valid reservation ID."
    );
}
    }//GEN-LAST:event_btnCheckOutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to exit?",
            "Exit Confirmation",
            JOptionPane.YES_NO_OPTION);

    if (choice == JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReservationGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbRoomNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReservations;
    private javax.swing.JTextField txtCheckInDate;
    private javax.swing.JTextField txtCheckOutDate;
    private javax.swing.JTextField txtGuestEmail;
    private javax.swing.JTextField txtGuestName;
    private javax.swing.JTextField txtGuestPhone;
    private javax.swing.JTextField txtPassportNumber;
    private javax.swing.JTextField txtReservationId;
    // End of variables declaration//GEN-END:variables
}
