/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package RestaurantMenu_TableManagement_m3;

/**
 *
 * @author Lolwah Al Ansari
 * Section: 01A
 */

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MenuPanel extends javax.swing.JPanel{
    
    private MenuManager menuManager;
    private FileHandler fileHandler;
    
    /**
     * Creates new form MenuPanel
     */
    public MenuPanel(boolean isAdmin) {
        initComponents();
        
        fileHandler = new FileHandler();
        menuManager = new MenuManager();
        menuManager.getAllMenuItems().addAll(fileHandler.loadMenu());
        
        if (!isAdmin) {
            btnAdd.setEnabled(false);
            btnUpdate.setEnabled(false);
            btnDelete.setEnabled(false);
        }
        refreshTable();
        
        tblMenu.setRowHeight(25);
    }
    
    private void refreshTable(){
        DefaultTableModel model = (DefaultTableModel) tblMenu.getModel();
        model.setRowCount(0);
        
        for (MenuItem item : menuManager.getAllMenuItems()) {
            model.addRow(new Object[]{
                item.getItemID(),
                item.getItemName(),
                item.getCategory(),
                item.getPrice(),
                item.getPreparationTime(),
                item.isAvailable()
            });
        }
    }
    
    private void clearFields(){
        txtItemID.setText("");
        txtItemName.setText("");
        txtPrice.setText("");
        txtPreparationTime.setText("");
        cmbCategory.setSelectedIndex(0);
        chkAvailable.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtItemID = new javax.swing.JTextField();
        txtItemName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtPreparationTime = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox<>();
        chkAvailable = new javax.swing.JCheckBox();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(1040, 640));

        jLabel1.setFont(new java.awt.Font("American Typewriter", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 99, 181));
        jLabel1.setText("Restaurant Menu Management");

        jLabel2.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setText("Item ID:");

        jLabel3.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setText("Item Name:");

        jLabel4.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("Category:");

        jLabel5.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 51, 0));
        jLabel5.setText("Price:");

        jLabel6.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 0));
        jLabel6.setText("Preparation Time:");

        jLabel7.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 51, 0));
        jLabel7.setText("Availability:");

        cmbCategory.setForeground(new java.awt.Color(153, 51, 0));
        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Starter", "Main Course", "Dessert", "Drink", "Snack" }));

        chkAvailable.setForeground(new java.awt.Color(153, 51, 0));
        chkAvailable.setText("Available");

        btnAdd.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(153, 51, 0));
        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(153, 51, 0));
        btnUpdate.setText("Update");
        btnUpdate.setPreferredSize(new java.awt.Dimension(85, 35));
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(153, 51, 0));
        btnDelete.setText("Delete");
        btnDelete.setPreferredSize(new java.awt.Dimension(85, 35));
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnSearch.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(153, 51, 0));
        btnSearch.setText("Search");
        btnSearch.setPreferredSize(new java.awt.Dimension(85, 35));
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        btnClear.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(153, 51, 0));
        btnClear.setText("Clear");
        btnClear.setPreferredSize(new java.awt.Dimension(85, 35));
        btnClear.addActionListener(this::btnClearActionPerformed);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 80));

        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Item ID", "Item Name", "Category", "Price", "Preparation Time", "Available"
            }
        ));
        jScrollPane1.setViewportView(tblMenu);

        jLabel8.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Manage menu items for your restaurant.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtItemName)
                                    .addComponent(cmbCategory, 0, 770, Short.MAX_VALUE)
                                    .addComponent(txtPrice)
                                    .addComponent(chkAvailable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPreparationTime)
                                    .addComponent(txtItemID, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(134, 134, 134)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(288, 288, 288))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(358, 358, 358))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtItemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPreparationTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(chkAvailable))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 343, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try {
            int itemId = Integer.parseInt(txtItemID.getText().trim());
            String itemName = txtItemName.getText().trim();
            String category = cmbCategory.getSelectedItem().toString();
            double price = Double.parseDouble(txtPrice.getText().trim());
            int preparationTime = Integer.parseInt(txtPreparationTime.getText().trim());
            boolean available = chkAvailable.isSelected();
            
            if (itemName.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter the item name.");
            return;
            }
            
            if (price <= 0){
            JOptionPane.showMessageDialog(this, "Price must be greater than 0.");
            return;
            }
            
            if (preparationTime <= 0){
            JOptionPane.showMessageDialog(this, "Preparation time must be greater than 0.");
            return;
            }
            
            if (menuManager.searchItem(itemId) != null) {
            JOptionPane.showMessageDialog(this, "Item ID already exists.");
            return;
            }
            
            MenuItem item = new MenuItem( itemId, itemName, category, price, preparationTime, available );
            
            menuManager.addMenuItem(item);
            
            fileHandler.saveMenu(menuManager.getAllMenuItems());
            
            refreshTable();
            
            clearFields();
            
            JOptionPane.showMessageDialog(this, "Menu item added successfully!");
            
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numeric values.");
        } 
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
            int itemId = Integer.parseInt(txtItemID.getText().trim());
            
            MenuItem item = menuManager.searchItem(itemId);
            
            if (item == null){
                JOptionPane.showMessageDialog(this, "Item not found.");
                return;
            }
            
            item.setItemName(txtItemName.getText().trim());
            item.setCategory(cmbCategory.getSelectedItem().toString());
            item.setPrice(Double.parseDouble(txtPrice.getText().trim()));
            item.setPreparationTime(Integer.parseInt(txtPreparationTime.getText().trim()));
            item.setAvailable(chkAvailable.isSelected());
            
            fileHandler.saveMenu(menuManager.getAllMenuItems());
            
            refreshTable();
            clearFields();
            
            JOptionPane.showMessageDialog(this, "Menu item updated successfully!");
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numeric values.");
        }   

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
            int row = tblMenu.getSelectedRow();
            
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Please select an item.");
                return;
            }
            
            int choice = JOptionPane.showConfirmDialog( this, "Are you sure you want to delete this item?","Delete Item",JOptionPane.YES_NO_OPTION);
            
            if (choice == JOptionPane.YES_OPTION) {
                menuManager.removeItem(row);
                DefaultTableModel model = (DefaultTableModel) tblMenu.getModel(); 
                
                refreshTable();
                fileHandler.saveMenu(menuManager.getAllMenuItems());
                clearFields(); 
                JOptionPane.showMessageDialog(this, "Item deleted successfully.");
            }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        try {
            int itemID = Integer.parseInt(txtItemID.getText());
            
            MenuItem item = menuManager.searchItem(itemID);
            if (item == null) {
                JOptionPane.showMessageDialog(this,"Item not found.");
                return;
            }
            
            txtItemName.setText(item.getItemName());
            cmbCategory.setSelectedItem(item.getCategory());
            txtPrice.setText(String.valueOf(item.getPrice()));
            txtPreparationTime.setText(String.valueOf(item.getPreparationTime()));
            chkAvailable.setSelected(item.isAvailable());
            
            for (int i = 0; i < tblMenu.getRowCount(); i++) {
                int id = Integer.parseInt( tblMenu.getValueAt(i, 0).toString());
                
                if (id == itemID) {
                    tblMenu.setRowSelectionInterval(i, i);
                    break;
                }
            }
        }catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Enter a valid Item ID."); 
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chkAvailable;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblMenu;
    private javax.swing.JTextField txtItemID;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtPreparationTime;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}