/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package RestaurantMenu_TableManagement_m3;

/**
 *
 * @author Lolwah Al Ansari
 * Section: 01A
 */

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MenuPanel extends javax.swing.JPanel{
    
    private MenuManager menuManager;
    private FileHandler fileHandler;
    
    /**
     * Creates new form MenuPanel
     */
    public MenuPanel() {
        initComponents();
        
        fileHandler = new FileHandler();
        menuManager = new MenuManager();
        menuManager.getAllMenuItems().addAll(fileHandler.loadMenu());
        
        refreshTable();
    }

private void refreshTable(){
    DefaultTableModel model = (DefaultTableModel) tblMenu.getModel();
    
    model.setRowCount(0);
    
    for (MenuItem item : menuManager.getAllMenuItems()) {
        model.addRow(new Object[]{
            item.getItemID(),
            item.getItemName(),
            item.getCategory(),
            item.getPrice(),
            item.getPreparationTime(),
            item.isAvailable()
        });
    }
}

private void clearFields(){
    txtItemID.setText("");
    txtItemName.setText("");
    txtPrice.setText("");
    txtPreparationTime.setText("");
    cmbCategory.setSelectedIndex(0);
    chkAvailable.setSelected(false);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtItemID = new javax.swing.JTextField();
        txtItemName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtPreparationTime = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox<>();
        chkAvailable = new javax.swing.JCheckBox();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Apple Chancery", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Resturant Menu Management");

        jLabel2.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setText("Item ID:");

        jLabel3.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setText("Item Name:");

        jLabel4.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("Category:");

        jLabel5.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 51, 0));
        jLabel5.setText("Price:");

        jLabel6.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 0));
        jLabel6.setText("Preparation Time:");

        jLabel7.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 51, 0));
        jLabel7.setText("Availability:");

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Starter", "Main Course", "Dessert", "Drink", "Snack" }));

        chkAvailable.setText("Available");

        btnAdd.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(153, 51, 0));
        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(153, 51, 0));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(153, 51, 0));
        btnDelete.setText("Delete");

        btnSearch.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(153, 51, 0));
        btnSearch.setText("Search");

        btnClear.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(153, 51, 0));
        btnClear.setText("Clear");

        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Item ID", "Item Name", "Category", "Price", "Preparation Time", "Available"
            }
        ));
        jScrollPane1.setViewportView(tblMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnAdd)
                                .addComponent(jLabel7)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdate)
                                .addGap(52, 52, 52)
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addComponent(btnSearch)
                                .addGap(44, 44, 44)
                                .addComponent(btnClear))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtItemName, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtItemID, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPrice)
                                    .addComponent(txtPreparationTime)
                                    .addComponent(cmbCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkAvailable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtItemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPreparationTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(chkAvailable))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnSearch)
                    .addComponent(btnClear))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try {
            int itemId = Integer.parseInt(txtItemID.getText().trim());
            String itemName = txtItemName.getText().trim();
            String category = cmbCategory.getSelectedItem().toString();
            double price = Double.parseDouble(txtPrice.getText().trim());
            int preparationTime = Integer.parseInt(txtPreparationTime.getText().trim());
            boolean available = chkAvailable.isSelected();
            
            if (itemName.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter the item name.");
            return;
            }
            
            if (price <= 0){
            JOptionPane.showMessageDialog(this, "Price must be greater than 0.");
            return;
            }
            
            if (preparationTime <= 0){
            JOptionPane.showMessageDialog(this, "Preparation time must be greater than 0.");
            return;
            }
            
            if (menuManager.searchMenuItem(itemId) != null) {
            JOptionPane.showMessageDialog(this, "Item ID already exists.");
            return;
            }
            
            MenuItem item = new MenuItem(
                itemId,
                itemName,
                category,
                price,
                preparationTime,
                available
            );
            
            menuManager.addMenuItem(item);
            
            fileHandler.saveMenu(menuManager.getAllMenuItems());
            
            refreshTable();
            
            clearFields();
            
            JOptionPane.showMessageDialog(this, "Menu item added successfully!");
            
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numeric values.");
        } 
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
            int itemId = Integer.parseInt(txtItemID.getText().trim());
            
            MenuItem item = menuManager.searchMenuItem(itemId);
            
            if (item == null){
                JOptionPane.showMessageDialog(this, "Item not found.");
                return;
            }
            
            item.setItemName(txtItemName.getText().trim());
            item.setCategory(cmbCategory.getSelectedItem().toString());
            item.setPrice(Double.parseDouble(txtPrice.getText().trim()));
            item.setPreparationTime(Integer.parseInt(txtPreparationTime.getText().trim()));
            item.setAvailable(chkAvailable.isSelected());
            
            fileHandler.saveMenu(menuManager.getAllMenuItems());
            
            refreshTable();
            clearFields();
            
            JOptionPane.showMessageDialog(this, "Menu item updated successfully!");
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numeric values.");
        }   

    }//GEN-LAST:event_btnUpdateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chkAvailable;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMenu;
    private javax.swing.JTextField txtItemID;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtPreparationTime;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}