/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package RestaurantMenu_TableManagement_m3;

/**
 *
 * @author Lolwah Al Ansari
 * Section: 01A
 */

import javax.swing.JOptionPane;

public class ReportsPanel extends javax.swing.JPanel {
    
    private FileHandler fileHandler;
    private MenuManager menuManager;
    private TableManager tableManager;
    
    /**
     * Creates new form ReportsPanel
     */
    public ReportsPanel() {
        initComponents();
        
        fileHandler = new FileHandler();
        menuManager = new MenuManager();
        tableManager = new TableManager();
        
        menuManager.getAllMenuItems().addAll(fileHandler.loadMenu());
        tableManager.getAllTables().addAll(fileHandler.loadTables());
        loadReport();
    }
    
    private void loadReport() {
        int totalMenu = menuManager.getAllMenuItems().size();
        
        int availableMenu = 0;
        int unavailableMenu = 0;
        
        for (MenuItem item : menuManager.getAllMenuItems()) {
            if (item.isAvailable()) {
                availableMenu++;
            } else {
                unavailableMenu++;
            }
        }
        
        int totalTables = tableManager.getAllTables().size();
        
        int availableTables = 0;
        int occupiedTables = 0;
        int reservedTables = 0;
        
        for (RestaurantTable table : tableManager.getAllTables()) {
            if (table.getStatus().equalsIgnoreCase("Available")) {
                availableTables++;
            }
            else if (table.getStatus().equalsIgnoreCase("Occupied")) {
                occupiedTables++;
            }
            else if (table.getStatus().equalsIgnoreCase("Reserved")) {
                reservedTables++;
            }
        }
        
        lblTotalMenu.setText(String.valueOf(totalMenu));
        lblAvailableMenu.setText(String.valueOf(availableMenu));
        lblUnavailableMenu.setText(String.valueOf(unavailableMenu));
        lblTotalTables.setText(String.valueOf(totalTables));
        lblAvailableTables.setText(String.valueOf(availableTables));
        lblOccupiedTables.setText(String.valueOf(occupiedTables));
        lblReservedTables.setText(String.valueOf(reservedTables));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTotalMenu = new javax.swing.JLabel();
        lblAvailableMenu = new javax.swing.JLabel();
        lblUnavailableMenu = new javax.swing.JLabel();
        lblTotalTables = new javax.swing.JLabel();
        lblAvailableTables = new javax.swing.JLabel();
        lblOccupiedTables = new javax.swing.JLabel();
        lblReservedTables = new javax.swing.JLabel();
        btnRefreshReport = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1040, 640));

        jLabel1.setFont(new java.awt.Font("American Typewriter", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 99, 181));
        jLabel1.setText("Restaurant Reports");

        jLabel2.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setText("Total Menu Items");

        jLabel3.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setText("Available Menu Items");

        jLabel4.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("Unavailable Menu Items");

        jLabel5.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 51, 0));
        jLabel5.setText("Total Tables:");

        jLabel6.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 0));
        jLabel6.setText("Available Tables:");

        jLabel7.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 51, 0));
        jLabel7.setText("Occupied Tables:");

        lblTotalMenu.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        lblTotalMenu.setText("0");

        lblAvailableMenu.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        lblAvailableMenu.setText("0");

        lblUnavailableMenu.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        lblUnavailableMenu.setText("0");

        lblTotalTables.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        lblTotalTables.setText("0");

        lblAvailableTables.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        lblAvailableTables.setText("0");

        lblOccupiedTables.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        lblOccupiedTables.setText("0");

        lblReservedTables.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        lblReservedTables.setText("0");

        btnRefreshReport.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        btnRefreshReport.setForeground(new java.awt.Color(153, 51, 0));
        btnRefreshReport.setText("Refresh Report");
        btnRefreshReport.setPreferredSize(new java.awt.Dimension(85, 35));
        btnRefreshReport.addActionListener(this::btnRefreshReportActionPerformed);

        jLabel8.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 51, 0));
        jLabel8.setText("Reserved Tables");

        jLabel9.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("View restaurant statistics and summaries.");

        jLabel10.setFont(new java.awt.Font("American Typewriter", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 204));
        jLabel10.setText("Menu Statistics");

        jLabel11.setFont(new java.awt.Font("American Typewriter", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 204));
        jLabel11.setText("Table Statistics");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(444, 444, 444)
                        .addComponent(btnRefreshReport, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAvailableMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUnavailableMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTotalMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addComponent(jLabel8))
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblReservedTables, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblOccupiedTables, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(56, 56, 56)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblAvailableTables, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblTotalTables, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addContainerGap(65, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(lblTotalMenu)
                    .addComponent(lblTotalTables))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(lblAvailableMenu)
                    .addComponent(lblAvailableTables))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(lblUnavailableMenu)
                    .addComponent(lblOccupiedTables))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblReservedTables))
                .addGap(44, 44, 44)
                .addComponent(btnRefreshReport, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshReportActionPerformed
        // TODO add your handling code here:
        menuManager.getAllMenuItems().clear();
        tableManager.getAllTables().clear();
        menuManager.getAllMenuItems().addAll(fileHandler.loadMenu());
        tableManager.getAllTables().addAll(fileHandler.loadTables());
        
        loadReport();
        
        JOptionPane.showMessageDialog(this, "Report updated successfully.");
    }//GEN-LAST:event_btnRefreshReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefreshReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAvailableMenu;
    private javax.swing.JLabel lblAvailableTables;
    private javax.swing.JLabel lblOccupiedTables;
    private javax.swing.JLabel lblReservedTables;
    private javax.swing.JLabel lblTotalMenu;
    private javax.swing.JLabel lblTotalTables;
    private javax.swing.JLabel lblUnavailableMenu;
    // End of variables declaration//GEN-END:variables
}
