/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package RestaurantMenu_TableManagement_m3;

/**
 *
 * @author Lolwah Al Ansari
 * Section: 01A
 */
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TablePanel extends javax.swing.JPanel {
    
    private TableManager tableManager;
    private FileHandler fileHandler;

    /**
     * Creates new form TablePanel
     */
    public TablePanel(boolean isAdmin) {
        initComponents();
        fileHandler = new FileHandler();
        tableManager = new TableManager();
        
        tableManager.getAllTables().addAll(fileHandler.loadTables());
        
        if (!isAdmin) {
            btnAdd.setEnabled(false);
            btnUpdate.setEnabled(false);
            btnDelete.setEnabled(false);
        }
        refreshTable(); 
        
        tblTables.setRowHeight(25);
    }
    
    private void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) tblTables.getModel();
        
        model.setRowCount(0);
        
        for (RestaurantTable table : tableManager.getAllTables()) {
            model.addRow(new Object[]{
                table.getTableID(), table.getTableNumber(), table.getSeatingCapacity(),table.getStatus() });
        }
    }
    
    private void clearFields() {
        txtTableID.setText("");
        txtTableNumber.setText("");
        txtCapacity.setText("");
        cmbStatus.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTableID = new javax.swing.JTextField();
        txtTableNumber = new javax.swing.JTextField();
        txtCapacity = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTables = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1040, 640));

        jLabel1.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 0));
        jLabel1.setText("Table ID:");

        jLabel2.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setText("Table Number:");

        jLabel3.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setText("Seating Capacity:");

        jLabel4.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("Status:");

        cmbStatus.setForeground(new java.awt.Color(153, 51, 0));
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Occupied", "Reserved" }));

        btnAdd.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(153, 51, 0));
        btnAdd.setText("Add");
        btnAdd.setPreferredSize(new java.awt.Dimension(85, 35));
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(153, 51, 0));
        btnUpdate.setText("Update");
        btnUpdate.setPreferredSize(new java.awt.Dimension(85, 35));
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(153, 51, 0));
        btnDelete.setText("Delete");
        btnDelete.setPreferredSize(new java.awt.Dimension(85, 35));
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnSearch.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(153, 51, 0));
        btnSearch.setText("Search");
        btnSearch.setPreferredSize(new java.awt.Dimension(85, 35));
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        btnClear.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(153, 51, 0));
        btnClear.setText("Clear");
        btnClear.setPreferredSize(new java.awt.Dimension(85, 35));
        btnClear.addActionListener(this::btnClearActionPerformed);

        tblTables.setForeground(new java.awt.Color(102, 51, 0));
        tblTables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Table ID", "Table Number", "Capacity", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblTables);

        jLabel5.setFont(new java.awt.Font("American Typewriter", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(33, 99, 181));
        jLabel5.setText("Restaurant Table Management");

        jLabel7.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Manage restaurant tables and seating.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTableNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTableID, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(52, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(142, 142, 142)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(140, 140, 140)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(366, 366, 366))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(303, 303, 303))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTableID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTableNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try {
            int tableID = Integer.parseInt(txtTableID.getText());
            int tableNumber = Integer.parseInt(txtTableNumber.getText());
            int seatingCapacity = Integer.parseInt(txtCapacity.getText());
            String status = cmbStatus.getSelectedItem().toString();
            
            if (tableID <= 0) {
                JOptionPane.showMessageDialog(this, "Table ID must be greater than 0.");
                return;
            }
            if (tableNumber <= 0) {
                JOptionPane.showMessageDialog(this, "Table Number must be greater than 0.");
                return;
            }
            if (seatingCapacity <= 0) {
                JOptionPane.showMessageDialog(this, "Seating Capacity must be greater than 0.");
                return;
            } 
            if (tableManager.searchTable(tableID) != null) {
                JOptionPane.showMessageDialog(this, "Table ID already exists.");
                return;
            }
            
            RestaurantTable table = new RestaurantTable( tableID, tableNumber, seatingCapacity, status);
            tableManager.addTable(table);
            fileHandler.saveTables(tableManager.getAllTables());
            refreshTable();
            clearFields();
            
            JOptionPane.showMessageDialog(this, "Table added successfully.");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numbers.");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        try {
            int tableID = Integer.parseInt(txtTableID.getText());
            RestaurantTable table = tableManager.searchTable(tableID);
            
            if (table != null) {
                txtTableNumber.setText(String.valueOf(table.getTableNumber()));
                txtCapacity.setText(String.valueOf(table.getSeatingCapacity()));
                cmbStatus.setSelectedItem(table.getStatus());
                JOptionPane.showMessageDialog(this, "Table found.");
            } else {
                JOptionPane.showMessageDialog(this, "Table not found.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Enter a valid Table ID.");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
            int tableID = Integer.parseInt(txtTableID.getText());
            int tableNumber = Integer.parseInt(txtTableNumber.getText());
            int seatingCapacity = Integer.parseInt(txtCapacity.getText());
            String status = cmbStatus.getSelectedItem().toString();
            
            if (tableID <= 0) {
                JOptionPane.showMessageDialog(this, "Table ID must be greater than 0.");
                return;
            }
            if (tableNumber <= 0) {
                JOptionPane.showMessageDialog(this, "Table Number must be greater than 0.");
                return;
            }
            if (seatingCapacity <= 0) {
                JOptionPane.showMessageDialog(this, "Seating Capacity must be greater than 0.");
                return;
            }

            boolean updated = tableManager.updateTable( tableID, tableNumber, seatingCapacity, status);
            
            if (updated){
                fileHandler.saveTables(tableManager.getAllTables());
                refreshTable();
                clearFields();
                JOptionPane.showMessageDialog(this, "Table updated successfully.");
            } else {
                JOptionPane.showMessageDialog(this,"Table not found.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numbers.");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            int tableID = Integer.parseInt(txtTableID.getText());
            boolean deleted = tableManager.deleteTable(tableID);
            
            if (deleted) {
                fileHandler.saveTables(tableManager.getAllTables());
                refreshTable();
                clearFields();
                JOptionPane.showMessageDialog(this, "Table deleted successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Table not found.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Enter a valid Table ID.");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_btnClearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTables;
    private javax.swing.JTextField txtCapacity;
    private javax.swing.JTextField txtTableID;
    private javax.swing.JTextField txtTableNumber;
    // End of variables declaration//GEN-END:variables
}
