/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RoomManagement_m1;

/**
 * Jana Salem 2241100402
 */

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class RoomManagementGUI extends javax.swing.JFrame {
    
    private RoomManager manager;
    private RoomFiles files;
    
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RoomManagementGUI.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public RoomManagementGUI() {
        initComponents();
        
        manager = new RoomManager();
        files = new RoomFiles(manager);
        
        files.loadRooms();
        loadTable();
        generateReport();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        titlelbl = new javax.swing.JLabel();
        roomnumlbl = new javax.swing.JLabel();
        floornumlbl = new javax.swing.JLabel();
        roomtyplbl = new javax.swing.JLabel();
        bedcountlbl = new javax.swing.JLabel();
        pricelbl = new javax.swing.JLabel();
        roomstatslbl = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        chkAC = new javax.swing.JCheckBox();
        chkWifi = new javax.swing.JCheckBox();
        chkTV = new javax.swing.JCheckBox();
        chkBalcony = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        txtroomnum = new javax.swing.JTextField();
        txtfloornum = new javax.swing.JTextField();
        txtbedcount = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        cmbxroomtyp = new javax.swing.JComboBox<>();
        cmbxstatus = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchlbl = new javax.swing.JLabel();
        txtsearchvalue = new javax.swing.JTextField();
        valuelbl = new javax.swing.JLabel();
        cmbxsearch = new javax.swing.JComboBox<>();
        btnsearch = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        totalroomslbl = new javax.swing.JLabel();
        availableroomslbl = new javax.swing.JLabel();
        reservedroomslbl = new javax.swing.JLabel();
        occupiedroomslbl = new javax.swing.JLabel();
        maintenanceroomslbl = new javax.swing.JLabel();
        txttotalrooms = new javax.swing.JLabel();
        txtavailablerooms = new javax.swing.JLabel();
        txtreservedrooms = new javax.swing.JLabel();
        txtoccupiedrooms = new javax.swing.JLabel();
        txtmaintenancerooms = new javax.swing.JLabel();
        btngenerate = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        statusrmnolbl = new javax.swing.JLabel();
        txtroomnumforupdate = new javax.swing.JTextField();
        newstatuslbl = new javax.swing.JLabel();
        cmbxnewstatus = new javax.swing.JComboBox<>();
        btnchangestatus = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnload = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        roomscroll = new javax.swing.JScrollPane();
        roomlisttbl = new javax.swing.JTable();
        btnexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        titlelbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        titlelbl.setText("Room Details");

        roomnumlbl.setText("Room Number:");

        floornumlbl.setText("Floor Number:");

        roomtyplbl.setText("Room Type:");

        bedcountlbl.setText("Bed Count:");

        pricelbl.setText("Price per Night:");

        roomstatslbl.setText("Room Status:");

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        chkAC.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        chkAC.setText("AC unit");
        chkAC.addActionListener(this::chkACActionPerformed);

        chkWifi.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        chkWifi.setText("Wifi Service");
        chkWifi.addActionListener(this::chkWifiActionPerformed);

        chkTV.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        chkTV.setText("TV Setup");

        chkBalcony.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        chkBalcony.setText("Balcony Availability");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel8.setText("Facilities");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkAC)
                    .addComponent(chkWifi)
                    .addComponent(chkTV)
                    .addComponent(chkBalcony))
                .addGap(0, 101, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkAC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chkWifi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkTV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkBalcony)
                .addGap(12, 12, 12))
        );

        cmbxroomtyp.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        cmbxroomtyp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Deluxe", "Suite", "Family" }));

        cmbxstatus.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        cmbxstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AVAILABLE", "RESERVED", "OCCUPIED", "MAINTENANCE" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roomnumlbl)
                    .addComponent(titlelbl)
                    .addComponent(pricelbl)
                    .addComponent(roomtyplbl)
                    .addComponent(bedcountlbl)
                    .addComponent(floornumlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(roomstatslbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbxstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtroomnum, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtbedcount, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbxroomtyp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtprice)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtfloornum, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titlelbl)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roomnumlbl)
                            .addComponent(txtroomnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfloornum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(floornumlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbxroomtyp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roomtyplbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbedcount, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bedcountlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pricelbl)
                            .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roomstatslbl, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(cmbxstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setText("Search Room");

        searchlbl.setText("Search by: ");

        valuelbl.setText("Value:");

        cmbxsearch.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        cmbxsearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Room Number", "Floor Number", "Room Type", "Room Status" }));

        btnsearch.setBackground(new java.awt.Color(204, 204, 204));
        btnsearch.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(this::btnsearchActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(185, 261, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(valuelbl)
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtsearchvalue)
                                .addGap(6, 6, 6))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(searchlbl)
                        .addGap(18, 18, 18)
                        .addComponent(cmbxsearch, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchlbl)
                    .addComponent(cmbxsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(valuelbl)
                    .addComponent(txtsearchvalue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setText("Overall Report");

        totalroomslbl.setText("Total Rooms: ");

        availableroomslbl.setText("Available Rooms:");

        reservedroomslbl.setText("Reserved Rooms:");

        occupiedroomslbl.setText("Occupied Rooms:");

        maintenanceroomslbl.setText("Maintenance Rooms:");

        txttotalrooms.setText("0");

        txtavailablerooms.setText("0");

        txtreservedrooms.setText("0");

        txtoccupiedrooms.setText("0");

        txtmaintenancerooms.setText("0");

        btngenerate.setBackground(new java.awt.Color(204, 204, 204));
        btngenerate.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        btngenerate.setText("Generate Report");
        btngenerate.addActionListener(this::btngenerateActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(maintenanceroomslbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addComponent(txtmaintenancerooms))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(occupiedroomslbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtoccupiedrooms))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(reservedroomslbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtreservedrooms))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(availableroomslbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtavailablerooms))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(totalroomslbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txttotalrooms))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btngenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addGap(27, 27, 27))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttotalrooms)
                    .addComponent(totalroomslbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtavailablerooms)
                    .addComponent(availableroomslbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtreservedrooms)
                    .addComponent(reservedroomslbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtoccupiedrooms)
                    .addComponent(occupiedroomslbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmaintenancerooms)
                    .addComponent(maintenanceroomslbl))
                .addGap(18, 18, 18)
                .addComponent(btngenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setText("Status Update ");

        statusrmnolbl.setText("Room Number :");

        newstatuslbl.setText("New Status:");

        cmbxnewstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AVAILABLE", "RESERVED", "OCCUPIED", "MAINTENANCE" }));

        btnchangestatus.setBackground(new java.awt.Color(204, 204, 204));
        btnchangestatus.setText("Change Status");
        btnchangestatus.addActionListener(this::btnchangestatusActionPerformed);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusrmnolbl)
                            .addComponent(newstatuslbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(btnchangestatus, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cmbxnewstatus, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtroomnumforupdate))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusrmnolbl)
                    .addComponent(txtroomnumforupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbxnewstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newstatuslbl))
                .addGap(18, 18, 18)
                .addComponent(btnchangestatus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnadd.setBackground(new java.awt.Color(204, 204, 204));
        btnadd.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        btnadd.setText("Add room");
        btnadd.addActionListener(this::btnaddActionPerformed);

        btnedit.setBackground(new java.awt.Color(204, 204, 204));
        btnedit.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        btnedit.setText("Edit room");
        btnedit.addActionListener(this::btneditActionPerformed);

        btndelete.setBackground(new java.awt.Color(204, 204, 204));
        btndelete.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        btndelete.setText("Delete room");
        btndelete.addActionListener(this::btndeleteActionPerformed);

        btnsave.setBackground(new java.awt.Color(204, 204, 204));
        btnsave.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(this::btnsaveActionPerformed);

        btnload.setBackground(new java.awt.Color(204, 204, 204));
        btnload.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        btnload.setText("Load ");
        btnload.addActionListener(this::btnloadActionPerformed);

        btnclear.setBackground(new java.awt.Color(204, 204, 204));
        btnclear.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(this::btnclearActionPerformed);

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel17.setText("Room List");

        roomscroll.setBackground(new java.awt.Color(255, 255, 255));

        roomlisttbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Room No.", "Floor No.", "Type", "Beds No.", "Price", "Status", "AC ", "WiFi", "TV", "Balcony"
            }
        ));
        roomscroll.setViewportView(roomlisttbl);

        btnexit.setBackground(new java.awt.Color(204, 204, 204));
        btnexit.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        btnexit.setText("Exit");
        btnexit.addActionListener(this::btnexitActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnadd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnedit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndelete)
                        .addGap(78, 78, 78)
                        .addComponent(btnsave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnload)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnclear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnexit))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(roomscroll, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnedit, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(btndelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnadd, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(btnclear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnexit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roomscroll, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkACActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkACActionPerformed

    private void chkWifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkWifiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkWifiActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        txtroomnum.setText("");
        txtfloornum.setText("");
        txtbedcount.setText("");
        txtprice.setText("");
        cmbxroomtyp.setSelectedIndex(0);
        cmbxstatus.setSelectedIndex(0);
        chkAC.setSelected(false);
        chkWifi.setSelected(false);
        chkTV.setSelected(false);
        chkBalcony.setSelected(false);  
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloadActionPerformed
        files.loadRooms();
        loadTable();
    }//GEN-LAST:event_btnloadActionPerformed

    
    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        if (txtroomnum.getText().trim().isEmpty() || txtfloornum.getText().trim().isEmpty()
        || txtbedcount.getText().trim().isEmpty() || txtprice.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this,
                "Please fill in all required fields.",
                "Missing Information",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        int roomNumber = Integer.parseInt(txtroomnum.getText());
        
        if(manager.searchRoomNumber(roomNumber) != null){

            JOptionPane.showMessageDialog(this,
                "Room number already exists.",
                "Duplicate Room",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int floorNumber = Integer.parseInt(txtfloornum.getText());
        String roomType = cmbxroomtyp.getSelectedItem().toString();
        int bedCount = Integer.parseInt(txtbedcount.getText());
        double price = Double.parseDouble(txtprice.getText());
        RoomStatus status = RoomStatus.valueOf(cmbxstatus.getSelectedItem().toString());
        boolean hasAC = chkAC.isSelected();
        boolean hasWifi = chkWifi.isSelected();
        boolean hasTV = chkTV.isSelected();
        boolean hasBalcony = chkBalcony.isSelected();
        
        
        
        Room r = new Room(roomNumber,floorNumber,roomType,bedCount,price,status,
            hasAC,hasWifi,hasTV,hasBalcony);
        
        manager.addRoom(r);
        loadTable(); 
        
        
        JOptionPane.showMessageDialog(this, "Room added successfully!");
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        files.saveRooms();
        JOptionPane.showMessageDialog(this,"Rooms saved successfully!");
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        int roomNumber = Integer.parseInt(txtroomnum.getText());
        
        if (manager.searchRoomNumber(roomNumber) == null) {
            JOptionPane.showMessageDialog(this,
            "Room not found.");
            return;
        }
        
        int choice = JOptionPane.showConfirmDialog(
        this, "Are you sure you want to delete this room?",
        "Delete Room",
        JOptionPane.YES_NO_OPTION);
        
        if(choice == JOptionPane.YES_OPTION){

            manager.deleteRoom(roomNumber);

            files.saveRooms();

            loadTable();
        }
        
        JOptionPane.showMessageDialog(this,"Room deleted successfully!");
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        int roomNumber = Integer.parseInt(txtroomnum.getText());
        int floorNumber = Integer.parseInt(txtfloornum.getText());
        String roomType = cmbxroomtyp.getSelectedItem().toString();
        int bedCount = Integer.parseInt(txtbedcount.getText());
        double pricePerNight = Double.parseDouble(txtprice.getText());
        RoomStatus roomStatus = RoomStatus.valueOf(cmbxstatus.getSelectedItem().toString());
        boolean hasAC = chkAC.isSelected();
        boolean hasWifi = chkWifi.isSelected();
        boolean hasTV = chkTV.isSelected();
        boolean hasBalcony = chkBalcony.isSelected();

        if(manager.searchRoomNumber(roomNumber)==null){

            JOptionPane.showMessageDialog(this,
            "Room not found.");
            return;
        }
        
        manager.editRoom(roomNumber, floorNumber, roomType, bedCount, pricePerNight, roomStatus, 
            hasAC, hasWifi, hasTV, hasBalcony);

        files.saveRooms();

        loadTable();
       
       
        JOptionPane.showMessageDialog(this, "Room updated successfully!");

    }//GEN-LAST:event_btneditActionPerformed

    private void btnchangestatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchangestatusActionPerformed
        int roomNumber = Integer.parseInt(txtroomnumforupdate.getText());

        if(manager.searchRoomNumber(roomNumber) == null){

            JOptionPane.showMessageDialog(this, "Room not found.");
            return;
        }
        
        RoomStatus roomStatus = RoomStatus.valueOf(cmbxnewstatus.getSelectedItem().toString());
        
        System.out.println("Room: " + roomNumber);
        System.out.println("New Status: " + roomStatus);
        manager.changeRoomStatus(roomNumber, roomStatus);
        
        files.saveRooms();
        loadTable();
       
        JOptionPane.showMessageDialog(this, "Room status updated successfully.");
    }//GEN-LAST:event_btnchangestatusActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        String search = cmbxsearch.getSelectedItem().toString();
        String value = txtsearchvalue.getText();
        
        if(search.equals("Room Number")){

            Room r = manager.searchRoomNumber(Integer.parseInt(value));

            DefaultTableModel model = (DefaultTableModel) roomlisttbl.getModel();

            model.setRowCount(0);

            if(r != null){

                model.addRow(new Object[]{
                    r.getRoomNumber(),r.getFloorNumber(),r.getRoomType(),r.getBedCount(),
                    r.getPricePerNight(),r.getRoomStatus(),r.getHasAC(),r.getHasWifi(),
                    r.getHasTV(),r.getHasBalcony()
                });
            }
        }
        
        else if(search.equals("Floor Number")){
            loadSearchTable(manager.searchFloorNumber(Integer.parseInt(value)));
        }
        
        else if(search.equals("Room Type")){
            loadSearchTable(manager.searchRoomType(value));
        }
        
        else if(search.equals("Room Status")){
            loadSearchTable(manager.searchRoomStatus(RoomStatus.valueOf(value.toUpperCase())));
        }   
        
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btngenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerateActionPerformed
        generateReport();
    }//GEN-LAST:event_btngenerateActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        int choice = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to exit?",
        "Exit",
        JOptionPane.YES_NO_OPTION);

        if(choice == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnexitActionPerformed

    
    private void loadTable(){

        DefaultTableModel model = (DefaultTableModel) roomlisttbl.getModel();

        model.setRowCount(0);
        
        for(Room r : manager.getRooms()){
            model.addRow(new Object[]{
                
                r.getRoomNumber(), r.getFloorNumber(),r.getRoomType(),r.getBedCount(),
                r.getPricePerNight(),r.getRoomStatus(),r.getHasAC(),r.getHasWifi(),
                r.getHasTV(),r.getHasBalcony()
            });
        }
    }
    
    private void loadSearchTable(ArrayList<Room> rooms){

        DefaultTableModel model = (DefaultTableModel) roomlisttbl.getModel();

        model.setRowCount(0);

        for(Room r : rooms){

            model.addRow(new Object[]{

                r.getRoomNumber(),r.getFloorNumber(),r.getRoomType(),
                r.getBedCount(),r.getPricePerNight(),r.getRoomStatus(),
                r.getHasAC(),r.getHasWifi(),r.getHasTV(),r.getHasBalcony()
            });
        }
    }
    
    private void generateReport() {

        int total = manager.getRooms().size();

        int available = 0;
        int reserved = 0;
        int occupied = 0;
        int maintenance = 0;

        for (Room r : manager.getRooms()) {

            switch (r.getRoomStatus()) {

            case AVAILABLE:
                available++;
                break;

            case RESERVED:
                reserved++;
                break;

            case OCCUPIED:
                occupied++;
                break;

            case MAINTENANCE:
                maintenance++;
                break;
            }
        }

        txttotalrooms.setText(String.valueOf(total));
        txtavailablerooms.setText(String.valueOf(available));
        txtreservedrooms.setText(String.valueOf(reserved));
        txtoccupiedrooms.setText(String.valueOf(occupied));
        txtmaintenancerooms.setText(String.valueOf(maintenance));
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RoomManagementGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availableroomslbl;
    private javax.swing.JLabel bedcountlbl;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnchangestatus;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btngenerate;
    private javax.swing.JButton btnload;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JCheckBox chkAC;
    private javax.swing.JCheckBox chkBalcony;
    private javax.swing.JCheckBox chkTV;
    private javax.swing.JCheckBox chkWifi;
    private javax.swing.JComboBox<String> cmbxnewstatus;
    private javax.swing.JComboBox<String> cmbxroomtyp;
    private javax.swing.JComboBox<String> cmbxsearch;
    private javax.swing.JComboBox<String> cmbxstatus;
    private javax.swing.JLabel floornumlbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel maintenanceroomslbl;
    private javax.swing.JLabel newstatuslbl;
    private javax.swing.JLabel occupiedroomslbl;
    private javax.swing.JLabel pricelbl;
    private javax.swing.JLabel reservedroomslbl;
    private javax.swing.JTable roomlisttbl;
    private javax.swing.JLabel roomnumlbl;
    private javax.swing.JScrollPane roomscroll;
    private javax.swing.JLabel roomstatslbl;
    private javax.swing.JLabel roomtyplbl;
    private javax.swing.JLabel searchlbl;
    private javax.swing.JLabel statusrmnolbl;
    private javax.swing.JLabel titlelbl;
    private javax.swing.JLabel totalroomslbl;
    private javax.swing.JLabel txtavailablerooms;
    private javax.swing.JTextField txtbedcount;
    private javax.swing.JTextField txtfloornum;
    private javax.swing.JLabel txtmaintenancerooms;
    private javax.swing.JLabel txtoccupiedrooms;
    private javax.swing.JTextField txtprice;
    private javax.swing.JLabel txtreservedrooms;
    private javax.swing.JTextField txtroomnum;
    private javax.swing.JTextField txtroomnumforupdate;
    private javax.swing.JTextField txtsearchvalue;
    private javax.swing.JLabel txttotalrooms;
    private javax.swing.JLabel valuelbl;
    // End of variables declaration//GEN-END:variables
}
